name: parking_web_app_maicero_shop
description: Parking web app to Maicero Shopping

publish_to: "none"

version: 0.1.10

supercash:
  platform:
    observability:
      sentryUrl: https://97688bea4b4843d69704ab7902dde14e@o1044928.ingest.sentry.io/6020182

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  auto_route: ^3.2.0
  barcode_widget: ^2.0.1
  bloc: ^7.0.0
  card_selector:
    git:
      url: https://github.com/victorbonnet/flutter_card_selector
      ref: 49e80c56c963e26925e226894496ab53b42e972a
  cpf_cnpj_validator: ^2.0.0
  credit_card_slider:
    git:
      url: https://github.com/GursheeshSingh/creditcard_slider
      ref: 35e1c7e7678b5b9e2f0bc0e858ccc0efdec137f3
  cupertino_icons: ^1.0.2
  dartx: ^0.7.1
  dartz: ^0.10.0-nullsafety.1
  device_info_plus: ^3.2.0
  device_info_plus_web: ^2.1.0
  dio: ^4.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_credit_card: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  flutter_verification_code: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  fluttericon: ^2.0.0
  freezed_annotation: ^0.14.1
  get_it: ^7.1.3
  hive: ^2.0.5
  http: ^0.13.3
  im_stepper: ^0.1.3
  injectable: ^1.2.2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  kt_dart: ^0.9.0
  logger: ^1.1.0
  lottie: ^1.0.1
  mocktail: ^0.2.0
  nanoid: ^1.0.0
  package_info_plus_web: ^1.0.4
  path_provider: ^2.0.1
  pretty_dio_logger: ^1.1.1
  rxdart: ^0.27.1
  sentry_flutter: ^6.2.2
  shared_preferences: ^2.0.11
  shared_preferences_web: ^2.0.2
  simple_animations: ^4.0.1
  stacked_card_carousel: ^0.0.3-nullsafety.1
  stop_watch_timer: ^1.3.1
  timeline_tile: ^2.0.0
  timezone: ^0.8.0
  uni_links: ^0.5.1
  uni_links_web: ^0.1.0
  uuid: ^3.0.5
  wifi_info_plugin_plus: ^2.0.2
  yaml: ^3.1.0

dev_dependencies:
  auto_route_generator: ^3.2.0
  bloc_test: ^8.1.0
  build_runner: ^2.1.5
  effective_dart: ^1.3.1
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2
  json_serializable: ^6.1.1
  lint: ^1.5.3
  mockito: ^5.0.14

flutter_icons:
  image_path: "assets/img/splash.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/img/
    - assets/svg/
    - config/
    - pubspec.yaml
    - resources/langs/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
